# yaml-language-server: $schema=https://json.schemastore.org/github-action
name: deploy-label
description: Derive the correct deploy suffix from the Github event

runs:
  using: composite
  steps:
    - uses: actions/github-scripts@v7
      id: workspace
      with:
        result-encoding: string
        script: |
          console.log(context)
          console.log(context.payload.pull_request)

          const labels = Array.isArray(context.payload.pull_request?.labels)
            ? context.payload.pull_request.labels.filter(l => `${l?.name}`.startsWith('deploy-'))
            : [];
          console.log(labels)
          return "deploy-dev1"

outputs:
  value:
    description: The derived label
    value: steps.workspace.outputs.result
