name: PR Deploy

on:
  pull_request:
    types:
      - labeled

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      false
      || contains(github.event.pull_request.labels.*.name, 'deploy-dev1')
      || contains(github.event.pull_request.labels.*.name, 'deploy-dev2')
      || contains(github.event.pull_request.labels.*.name, 'deploy-dev3')
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-lambda-edge-authorizer
          role-session-name: lambda-edge-authorizer-${{github.event.pull_request.number}}
          aws-region: us-east-1

      - uses: actions/checkout@v4

      - uses: ./.github/actions/derive-deploy-label
        id: label

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci
      - run: npm run test:unit
      - run: npm run build

      - run: npm run deploy
        env:
          CDK_STACK_PREFIX: lambda-edge-authorizer-${{steps.label.outputs.result}}
          SUBDOMAIN_PREFIX: ${{steps.label.outputs.value}}

      #- run: npm run test:e2e
